### ISSUE TITLE
Error: Cannot find module 'undici/lib/handler/redirect'

### ISSUE THREAD

**Issue by ThorQin** [3846masa/http-cookie-agent#281]
## Describe the bug

After upgrade undici to 5.11.0, app throw exception. undici 5.10.0 worked fine.
```
App threw an error during load
Error: Cannot find module 'undici/lib/handler/redirect'
Require stack:
  C:\Workspace\ydy-native-pc\node_modules\http-cookie-agent\dist\undici\cookie_client.js
  C:\Workspace\ydy-native-pc\node_modules\http-cookie-agent\dist\undici\cookie_agent.js
  C:\Workspace\ydy-native-pc\node_modules\http-cookie-agent\dist\undici\index.js
  C:\Workspace\ydy-native-pc\node_modules\http-cookie-agent\undici\index.js
  C:\Workspace\ydy-native-pc\build\app.js
  C:\Workspace\ydy-native-pc\node_modules\electron\dist\resources\default_app.asar\main.js
```

## Expected behavior

Should not throw exception.

## Environments

- http-cookie-agent version: 4.0.2
- undici version: 5.11.0
- electron version: 19.1.2
- OS version: windows10 x86_64

**Comment by 3846masa** [comment]
Sorry for the late response.
We are working on a fix, but our CI configuration is not working and we have not been able to deploy.
We will have it ready to use in a few days.

**Comment by 3846masa** [comment]
v5.0.0 released.
Please try it.
